/* Generated by Pyrex 0.9.5.1a on Fri Aug 10 19:29:22 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "csurface.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from psurface */



/* Implementation of psurface */

static PyObject *__pyx_n_CreateSurface;
static PyObject *__pyx_n_CollisionDetection;

static PyObject *__pyx_n_range;
static PyObject *__pyx_n_append;

static PyObject *__pyx_f_8psurface_CreateSurface(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8psurface_CreateSurface(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_spheres = 0;
  PyObject *__pyx_v_level = 0;
  PyObject *__pyx_v_method = 0;
  PyObject *__pyx_v_s;
  PyObject *__pyx_v_points;
  PyObject *__pyx_v_normals;
  PyObject *__pyx_v_colors;
  PyObject *__pyx_v_i;
  PyObject *__pyx_v_entities;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  double __pyx_4;
  double __pyx_5;
  double __pyx_6;
  double __pyx_7;
  int __pyx_8;
  PyObject *__pyx_9 = 0;
  PyObject *__pyx_10 = 0;
  PyObject *__pyx_11 = 0;
  PyObject *__pyx_12 = 0;
  PyObject *__pyx_13 = 0;
  static char *__pyx_argnames[] = {"spheres","level","method",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_spheres, &__pyx_v_level, &__pyx_v_method)) return 0;
  Py_INCREF(__pyx_v_spheres);
  Py_INCREF(__pyx_v_level);
  Py_INCREF(__pyx_v_method);
  __pyx_v_s = Py_None; Py_INCREF(Py_None);
  __pyx_v_points = Py_None; Py_INCREF(Py_None);
  __pyx_v_normals = Py_None; Py_INCREF(Py_None);
  __pyx_v_colors = Py_None; Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);
  __pyx_v_entities = Py_None; Py_INCREF(Py_None);

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":22 */
  cAllocate();

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":23 */
  __pyx_1 = PyObject_GetIter(__pyx_v_spheres); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
  for (;;) {
    __pyx_2 = PyIter_Next(__pyx_1);
    if (!__pyx_2) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_s);
    __pyx_v_s = __pyx_2;
    __pyx_2 = 0;

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":24 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_s, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_4 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyInt_FromLong(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_s, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_5 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyInt_FromLong(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_s, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_6 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyInt_FromLong(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_s, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_7 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyInt_FromLong(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_s, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_8 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    cAdd(__pyx_4,__pyx_5,__pyx_6,__pyx_7,__pyx_8);
  }
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":25 */
  __pyx_8 = PyInt_AsLong(__pyx_v_level); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
  cLevel(__pyx_8);

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":26 */
  __pyx_8 = PyInt_AsLong(__pyx_v_method); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  cMethod(__pyx_8);

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":27 */
  cCreateSurface();

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":28 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  Py_DECREF(__pyx_v_points);
  __pyx_v_points = __pyx_2;
  __pyx_2 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":29 */
  __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  Py_DECREF(__pyx_v_normals);
  __pyx_v_normals = __pyx_3;
  __pyx_3 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":30 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  Py_DECREF(__pyx_v_colors);
  __pyx_v_colors = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":31 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(cNp()); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_2 = PyObject_GetIter(__pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    __pyx_1 = PyIter_Next(__pyx_2);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_1;
    __pyx_1 = 0;

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":32 */
    __pyx_3 = PyObject_GetAttr(__pyx_v_points, __pyx_n_append); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_1 = PyFloat_FromDouble(cPx(__pyx_8)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_9 = PyFloat_FromDouble(cPy(__pyx_8)); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_10 = PyFloat_FromDouble(cPz(__pyx_8)); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_11 = PyTuple_New(3); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_11, 0, __pyx_1);
    PyTuple_SET_ITEM(__pyx_11, 1, __pyx_9);
    PyTuple_SET_ITEM(__pyx_11, 2, __pyx_10);
    __pyx_1 = 0;
    __pyx_9 = 0;
    __pyx_10 = 0;
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_11);
    __pyx_11 = 0;
    __pyx_9 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_9); __pyx_9 = 0;

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":33 */
    __pyx_10 = PyObject_GetAttr(__pyx_v_normals, __pyx_n_append); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    __pyx_11 = PyFloat_FromDouble(cNx(__pyx_8)); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    __pyx_3 = PyFloat_FromDouble(cNy(__pyx_8)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    __pyx_1 = PyFloat_FromDouble(cNz(__pyx_8)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    __pyx_9 = PyTuple_New(3); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_9, 0, __pyx_11);
    PyTuple_SET_ITEM(__pyx_9, 1, __pyx_3);
    PyTuple_SET_ITEM(__pyx_9, 2, __pyx_1);
    __pyx_11 = 0;
    __pyx_3 = 0;
    __pyx_1 = 0;
    __pyx_11 = PyTuple_New(1); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_11, 0, __pyx_9);
    __pyx_9 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_10, __pyx_11); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    Py_DECREF(__pyx_10); __pyx_10 = 0;
    Py_DECREF(__pyx_11); __pyx_11 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":34 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_colors, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
    __pyx_9 = PyInt_FromLong(cC(__pyx_8)); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
    __pyx_10 = PyTuple_New(1); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_10, 0, __pyx_9);
    __pyx_9 = 0;
    __pyx_11 = PyObject_CallObject(__pyx_1, __pyx_10); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_10); __pyx_10 = 0;
    Py_DECREF(__pyx_11); __pyx_11 = 0;
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":35 */
  __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
  Py_DECREF(__pyx_v_entities);
  __pyx_v_entities = __pyx_3;
  __pyx_3 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":36 */
  __pyx_8 = (cType() == 0);
  if (__pyx_8) {

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":37 */
    __pyx_9 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
    __pyx_1 = PyInt_FromLong((cNt() / 3)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
    __pyx_10 = PyTuple_New(1); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_10, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_11 = PyObject_CallObject(__pyx_9, __pyx_10); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
    Py_DECREF(__pyx_9); __pyx_9 = 0;
    Py_DECREF(__pyx_10); __pyx_10 = 0;
    __pyx_2 = PyObject_GetIter(__pyx_11); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
    Py_DECREF(__pyx_11); __pyx_11 = 0;
    for (;;) {
      __pyx_3 = PyIter_Next(__pyx_2);
      if (!__pyx_3) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
        break;
      }
      Py_DECREF(__pyx_v_i);
      __pyx_v_i = __pyx_3;
      __pyx_3 = 0;

      /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":38 */
      __pyx_1 = PyObject_GetAttr(__pyx_v_entities, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      __pyx_9 = PyInt_FromLong(3); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      __pyx_10 = PyNumber_Multiply(__pyx_9, __pyx_v_i); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_10); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      __pyx_11 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(3); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      __pyx_9 = PyNumber_Multiply(__pyx_3, __pyx_v_i); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_10 = PyInt_FromLong(1); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      __pyx_3 = PyNumber_Add(__pyx_9, __pyx_10); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_9 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      __pyx_10 = PyInt_FromLong(3); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      __pyx_3 = PyNumber_Multiply(__pyx_10, __pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      __pyx_10 = PyInt_FromLong(2); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      __pyx_12 = PyNumber_Add(__pyx_3, __pyx_10); if (!__pyx_12) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_12); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      Py_DECREF(__pyx_12); __pyx_12 = 0;
      __pyx_3 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      __pyx_10 = PyTuple_New(3); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_10, 0, __pyx_11);
      PyTuple_SET_ITEM(__pyx_10, 1, __pyx_9);
      PyTuple_SET_ITEM(__pyx_10, 2, __pyx_3);
      __pyx_11 = 0;
      __pyx_9 = 0;
      __pyx_3 = 0;
      __pyx_12 = PyTuple_New(1); if (!__pyx_12) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_12, 0, __pyx_10);
      __pyx_10 = 0;
      __pyx_11 = PyObject_CallObject(__pyx_1, __pyx_12); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_12); __pyx_12 = 0;
      Py_DECREF(__pyx_11); __pyx_11 = 0;
    }
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L6;
  }
  /*else*/ {

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":40 */
    __pyx_9 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong((cNt() / 4)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    __pyx_10 = PyTuple_New(1); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_10, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_9, __pyx_10); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    Py_DECREF(__pyx_9); __pyx_9 = 0;
    Py_DECREF(__pyx_10); __pyx_10 = 0;
    __pyx_12 = PyObject_GetIter(__pyx_1); if (!__pyx_12) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    for (;;) {
      __pyx_11 = PyIter_Next(__pyx_12);
      if (!__pyx_11) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
        break;
      }
      Py_DECREF(__pyx_v_i);
      __pyx_v_i = __pyx_11;
      __pyx_11 = 0;

      /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":41 */
      __pyx_2 = PyObject_GetAttr(__pyx_v_entities, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_9 = PyNumber_Multiply(__pyx_3, __pyx_v_i); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_9); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_10 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_1 = PyInt_FromLong(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_11 = PyNumber_Multiply(__pyx_1, __pyx_v_i); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_3 = PyInt_FromLong(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_9 = PyNumber_Add(__pyx_11, __pyx_3); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_11); __pyx_11 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_9); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_1 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_11 = PyInt_FromLong(4); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_3 = PyNumber_Multiply(__pyx_11, __pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_11); __pyx_11 = 0;
      __pyx_9 = PyInt_FromLong(2); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_11 = PyNumber_Add(__pyx_3, __pyx_9); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_11); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_11); __pyx_11 = 0;
      __pyx_3 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_9 = PyInt_FromLong(4); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_11 = PyNumber_Multiply(__pyx_9, __pyx_v_i); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_9 = PyInt_FromLong(3); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_13 = PyNumber_Add(__pyx_11, __pyx_9); if (!__pyx_13) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_11); __pyx_11 = 0;
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_13); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_13); __pyx_13 = 0;
      __pyx_11 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      __pyx_9 = PyTuple_New(4); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_9, 0, __pyx_10);
      PyTuple_SET_ITEM(__pyx_9, 1, __pyx_1);
      PyTuple_SET_ITEM(__pyx_9, 2, __pyx_3);
      PyTuple_SET_ITEM(__pyx_9, 3, __pyx_11);
      __pyx_10 = 0;
      __pyx_1 = 0;
      __pyx_3 = 0;
      __pyx_11 = 0;
      __pyx_13 = PyTuple_New(1); if (!__pyx_13) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_13, 0, __pyx_9);
      __pyx_9 = 0;
      __pyx_10 = PyObject_CallObject(__pyx_2, __pyx_13); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_13); __pyx_13 = 0;
      Py_DECREF(__pyx_10); __pyx_10 = 0;
    }
    Py_DECREF(__pyx_12); __pyx_12 = 0;
  }
  __pyx_L6:;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":42 */
  cFree();

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":43 */
  __pyx_1 = PyTuple_New(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  Py_INCREF(__pyx_v_entities);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_entities);
  Py_INCREF(__pyx_v_points);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_points);
  Py_INCREF(__pyx_v_colors);
  PyTuple_SET_ITEM(__pyx_1, 2, __pyx_v_colors);
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  Py_INCREF(__pyx_v_normals);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_normals);
  __pyx_1 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_9);
  Py_XDECREF(__pyx_10);
  Py_XDECREF(__pyx_11);
  Py_XDECREF(__pyx_12);
  Py_XDECREF(__pyx_13);
  __Pyx_AddTraceback("psurface.CreateSurface");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_points);
  Py_DECREF(__pyx_v_normals);
  Py_DECREF(__pyx_v_colors);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_entities);
  Py_DECREF(__pyx_v_spheres);
  Py_DECREF(__pyx_v_level);
  Py_DECREF(__pyx_v_method);
  return __pyx_r;
}

static PyObject *__pyx_f_8psurface_CollisionDetection(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8psurface_CollisionDetection(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_spheres = 0;
  PyObject *__pyx_v_level = 0;
  PyObject *__pyx_v_method = 0;
  PyObject *__pyx_v_delta = 0;
  PyObject *__pyx_v_s;
  PyObject *__pyx_v_points;
  PyObject *__pyx_v_normals;
  PyObject *__pyx_v_colors;
  PyObject *__pyx_v_i;
  PyObject *__pyx_v_entities;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  double __pyx_4;
  double __pyx_5;
  double __pyx_6;
  double __pyx_7;
  int __pyx_8;
  PyObject *__pyx_9 = 0;
  PyObject *__pyx_10 = 0;
  PyObject *__pyx_11 = 0;
  PyObject *__pyx_12 = 0;
  PyObject *__pyx_13 = 0;
  static char *__pyx_argnames[] = {"spheres","level","method","delta",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO", __pyx_argnames, &__pyx_v_spheres, &__pyx_v_level, &__pyx_v_method, &__pyx_v_delta)) return 0;
  Py_INCREF(__pyx_v_spheres);
  Py_INCREF(__pyx_v_level);
  Py_INCREF(__pyx_v_method);
  Py_INCREF(__pyx_v_delta);
  __pyx_v_s = Py_None; Py_INCREF(Py_None);
  __pyx_v_points = Py_None; Py_INCREF(Py_None);
  __pyx_v_normals = Py_None; Py_INCREF(Py_None);
  __pyx_v_colors = Py_None; Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);
  __pyx_v_entities = Py_None; Py_INCREF(Py_None);

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":45 */
  cAllocate();

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":46 */
  __pyx_1 = PyObject_GetIter(__pyx_v_spheres); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  for (;;) {
    __pyx_2 = PyIter_Next(__pyx_1);
    if (!__pyx_2) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_s);
    __pyx_v_s = __pyx_2;
    __pyx_2 = 0;

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":47 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_s, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_4 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyInt_FromLong(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_s, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_5 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyInt_FromLong(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_s, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_6 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyInt_FromLong(3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_s, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_7 = PyFloat_AsDouble(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyInt_FromLong(4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(__pyx_v_s, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_8 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    cAdd(__pyx_4,__pyx_5,__pyx_6,__pyx_7,__pyx_8);
  }
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":48 */
  __pyx_8 = PyInt_AsLong(__pyx_v_level); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
  cLevel(__pyx_8);

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":49 */
  __pyx_8 = PyInt_AsLong(__pyx_v_method); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
  cMethod(__pyx_8);

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":50 */
  __pyx_4 = PyFloat_AsDouble(__pyx_v_delta); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  cCollisionDetection(__pyx_4);

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":51 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
  Py_DECREF(__pyx_v_points);
  __pyx_v_points = __pyx_2;
  __pyx_2 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":52 */
  __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
  Py_DECREF(__pyx_v_normals);
  __pyx_v_normals = __pyx_3;
  __pyx_3 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":53 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; goto __pyx_L1;}
  Py_DECREF(__pyx_v_colors);
  __pyx_v_colors = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":54 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(cNp()); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_2 = PyObject_GetIter(__pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    __pyx_1 = PyIter_Next(__pyx_2);
    if (!__pyx_1) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_1;
    __pyx_1 = 0;

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":55 */
    __pyx_3 = PyObject_GetAttr(__pyx_v_points, __pyx_n_append); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_1 = PyFloat_FromDouble(cPx(__pyx_8)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_9 = PyFloat_FromDouble(cPy(__pyx_8)); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_10 = PyFloat_FromDouble(cPz(__pyx_8)); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    __pyx_11 = PyTuple_New(3); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_11, 0, __pyx_1);
    PyTuple_SET_ITEM(__pyx_11, 1, __pyx_9);
    PyTuple_SET_ITEM(__pyx_11, 2, __pyx_10);
    __pyx_1 = 0;
    __pyx_9 = 0;
    __pyx_10 = 0;
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_11);
    __pyx_11 = 0;
    __pyx_9 = PyObject_CallObject(__pyx_3, __pyx_1); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_9); __pyx_9 = 0;

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":56 */
    __pyx_10 = PyObject_GetAttr(__pyx_v_normals, __pyx_n_append); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_11 = PyFloat_FromDouble(cNx(__pyx_8)); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_3 = PyFloat_FromDouble(cNy(__pyx_8)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_1 = PyFloat_FromDouble(cNz(__pyx_8)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    __pyx_9 = PyTuple_New(3); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_9, 0, __pyx_11);
    PyTuple_SET_ITEM(__pyx_9, 1, __pyx_3);
    PyTuple_SET_ITEM(__pyx_9, 2, __pyx_1);
    __pyx_11 = 0;
    __pyx_3 = 0;
    __pyx_1 = 0;
    __pyx_11 = PyTuple_New(1); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_11, 0, __pyx_9);
    __pyx_9 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_10, __pyx_11); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
    Py_DECREF(__pyx_10); __pyx_10 = 0;
    Py_DECREF(__pyx_11); __pyx_11 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":57 */
    __pyx_1 = PyObject_GetAttr(__pyx_v_colors, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_8 = PyInt_AsLong(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_9 = PyInt_FromLong(cC(__pyx_8)); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    __pyx_10 = PyTuple_New(1); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_10, 0, __pyx_9);
    __pyx_9 = 0;
    __pyx_11 = PyObject_CallObject(__pyx_1, __pyx_10); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_10); __pyx_10 = 0;
    Py_DECREF(__pyx_11); __pyx_11 = 0;
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":58 */
  __pyx_3 = PyList_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  Py_DECREF(__pyx_v_entities);
  __pyx_v_entities = __pyx_3;
  __pyx_3 = 0;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":59 */
  __pyx_8 = (cType() == 0);
  if (__pyx_8) {

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":60 */
    __pyx_9 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    __pyx_1 = PyInt_FromLong((cNt() / 3)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    __pyx_10 = PyTuple_New(1); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_10, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_11 = PyObject_CallObject(__pyx_9, __pyx_10); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    Py_DECREF(__pyx_9); __pyx_9 = 0;
    Py_DECREF(__pyx_10); __pyx_10 = 0;
    __pyx_2 = PyObject_GetIter(__pyx_11); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
    Py_DECREF(__pyx_11); __pyx_11 = 0;
    for (;;) {
      __pyx_3 = PyIter_Next(__pyx_2);
      if (!__pyx_3) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
        break;
      }
      Py_DECREF(__pyx_v_i);
      __pyx_v_i = __pyx_3;
      __pyx_3 = 0;

      /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":61 */
      __pyx_1 = PyObject_GetAttr(__pyx_v_entities, __pyx_n_append); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_9 = PyInt_FromLong(3); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_10 = PyNumber_Multiply(__pyx_9, __pyx_v_i); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_10); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      __pyx_11 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(3); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_9 = PyNumber_Multiply(__pyx_3, __pyx_v_i); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_10 = PyInt_FromLong(1); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_3 = PyNumber_Add(__pyx_9, __pyx_10); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_9 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_10 = PyInt_FromLong(3); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_3 = PyNumber_Multiply(__pyx_10, __pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      __pyx_10 = PyInt_FromLong(2); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_12 = PyNumber_Add(__pyx_3, __pyx_10); if (!__pyx_12) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_10); __pyx_10 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_12); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_12); __pyx_12 = 0;
      __pyx_3 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      __pyx_10 = PyTuple_New(3); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_10, 0, __pyx_11);
      PyTuple_SET_ITEM(__pyx_10, 1, __pyx_9);
      PyTuple_SET_ITEM(__pyx_10, 2, __pyx_3);
      __pyx_11 = 0;
      __pyx_9 = 0;
      __pyx_3 = 0;
      __pyx_12 = PyTuple_New(1); if (!__pyx_12) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_12, 0, __pyx_10);
      __pyx_10 = 0;
      __pyx_11 = PyObject_CallObject(__pyx_1, __pyx_12); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      Py_DECREF(__pyx_12); __pyx_12 = 0;
      Py_DECREF(__pyx_11); __pyx_11 = 0;
    }
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L6;
  }
  /*else*/ {

    /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":63 */
    __pyx_9 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong((cNt() / 4)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    __pyx_10 = PyTuple_New(1); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_10, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_1 = PyObject_CallObject(__pyx_9, __pyx_10); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_DECREF(__pyx_9); __pyx_9 = 0;
    Py_DECREF(__pyx_10); __pyx_10 = 0;
    __pyx_12 = PyObject_GetIter(__pyx_1); if (!__pyx_12) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    for (;;) {
      __pyx_11 = PyIter_Next(__pyx_12);
      if (!__pyx_11) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; goto __pyx_L1;}
        break;
      }
      Py_DECREF(__pyx_v_i);
      __pyx_v_i = __pyx_11;
      __pyx_11 = 0;

      /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":64 */
      __pyx_2 = PyObject_GetAttr(__pyx_v_entities, __pyx_n_append); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_3 = PyInt_FromLong(4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_9 = PyNumber_Multiply(__pyx_3, __pyx_v_i); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_9); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_10 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_1 = PyInt_FromLong(4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_11 = PyNumber_Multiply(__pyx_1, __pyx_v_i); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_3 = PyInt_FromLong(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_9 = PyNumber_Add(__pyx_11, __pyx_3); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_11); __pyx_11 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_9); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_1 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_11 = PyInt_FromLong(4); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_3 = PyNumber_Multiply(__pyx_11, __pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_11); __pyx_11 = 0;
      __pyx_9 = PyInt_FromLong(2); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_11 = PyNumber_Add(__pyx_3, __pyx_9); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_11); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_11); __pyx_11 = 0;
      __pyx_3 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_9 = PyInt_FromLong(4); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_11 = PyNumber_Multiply(__pyx_9, __pyx_v_i); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_9 = PyInt_FromLong(3); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_13 = PyNumber_Add(__pyx_11, __pyx_9); if (!__pyx_13) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_11); __pyx_11 = 0;
      Py_DECREF(__pyx_9); __pyx_9 = 0;
      __pyx_8 = PyInt_AsLong(__pyx_13); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_13); __pyx_13 = 0;
      __pyx_11 = PyInt_FromLong(cI(__pyx_8)); if (!__pyx_11) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      __pyx_9 = PyTuple_New(4); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_9, 0, __pyx_10);
      PyTuple_SET_ITEM(__pyx_9, 1, __pyx_1);
      PyTuple_SET_ITEM(__pyx_9, 2, __pyx_3);
      PyTuple_SET_ITEM(__pyx_9, 3, __pyx_11);
      __pyx_10 = 0;
      __pyx_1 = 0;
      __pyx_3 = 0;
      __pyx_11 = 0;
      __pyx_13 = PyTuple_New(1); if (!__pyx_13) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_13, 0, __pyx_9);
      __pyx_9 = 0;
      __pyx_10 = PyObject_CallObject(__pyx_2, __pyx_13); if (!__pyx_10) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_13); __pyx_13 = 0;
      Py_DECREF(__pyx_10); __pyx_10 = 0;
    }
    Py_DECREF(__pyx_12); __pyx_12 = 0;
  }
  __pyx_L6:;

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":65 */
  __pyx_1 = PyTuple_New(3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  Py_INCREF(__pyx_v_entities);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_entities);
  Py_INCREF(__pyx_v_points);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_points);
  Py_INCREF(__pyx_v_colors);
  PyTuple_SET_ITEM(__pyx_1, 2, __pyx_v_colors);
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  Py_INCREF(__pyx_v_normals);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_normals);
  __pyx_1 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_9);
  Py_XDECREF(__pyx_10);
  Py_XDECREF(__pyx_11);
  Py_XDECREF(__pyx_12);
  Py_XDECREF(__pyx_13);
  __Pyx_AddTraceback("psurface.CollisionDetection");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_points);
  Py_DECREF(__pyx_v_normals);
  Py_DECREF(__pyx_v_colors);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_entities);
  Py_DECREF(__pyx_v_spheres);
  Py_DECREF(__pyx_v_level);
  Py_DECREF(__pyx_v_method);
  Py_DECREF(__pyx_v_delta);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_CollisionDetection, "CollisionDetection"},
  {&__pyx_n_CreateSurface, "CreateSurface"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_range, "range"},
  {0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"CreateSurface", (PyCFunction)__pyx_f_8psurface_CreateSurface, METH_VARARGS|METH_KEYWORDS, 0},
  {"CollisionDetection", (PyCFunction)__pyx_f_8psurface_CollisionDetection, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initpsurface(void); /*proto*/
PyMODINIT_FUNC initpsurface(void) {
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("psurface", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};

  /* "/home/jbk/DANSE/cad/src/experimental/oleksandr/psurface.pyx":44 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("psurface");
}

static char *__pyx_filenames[] = {
  "psurface.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
