/* Generated by Pyrex 0.9.3.1 on Sat Jun  2 11:33:10 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

static char __pyx_mdoc[] = "\npyrex_test.pyx\n\nExperimental Pyrex code, for testing use of Pyrex in nE-1.\n\n$Id: pyrex_test.pyx,v 1.4 2007/05/17 18:16:18 emessick Exp $\n\nFor plans and status related to our use of Pyrex, see:\n\n  http://www.nanoengineer-1.net/mediawiki/index.php?title=Integrating_Pyrex_into_the_Build_System\n\nSee README-Pyrex for the list of related files and their roles.\n\n";

/* Declarations from pyrex_test */


/* Implementation of pyrex_test */


static PyObject *__pyx_n___author__;
static PyObject *__pyx_n_nbonds;
static PyObject *__pyx_n_bruce;

static PyObject *__pyx_n_len;
static PyObject *__pyx_n_atoms;
static PyObject *__pyx_n_itervalues;
static PyObject *__pyx_n_bonds;

static PyObject *__pyx_f_10pyrex_test_nbonds(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10pyrex_test_nbonds[] = "Given a list of chunks, return the number of bonds on all their atoms\n    (counting bonds twice if both their atoms are in chunks in the list).\n    ";
static PyObject *__pyx_f_10pyrex_test_nbonds(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_mols = 0;
  int __pyx_v_tot;
  int __pyx_v_nn;
  PyObject *__pyx_v_i;
  PyObject *__pyx_v_mol;
  PyObject *__pyx_v_atm;
  PyObject *__pyx_v_bonds;
  PyObject *__pyx_r;
  long __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  long __pyx_5;
  PyObject *__pyx_6 = 0;
  int __pyx_7;
  static char *__pyx_argnames[] = {"mols",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_mols)) return 0;
  Py_INCREF(__pyx_v_mols);
  __pyx_v_i = Py_None; Py_INCREF(__pyx_v_i);
  __pyx_v_mol = Py_None; Py_INCREF(__pyx_v_mol);
  __pyx_v_atm = Py_None; Py_INCREF(__pyx_v_atm);
  __pyx_v_bonds = Py_None; Py_INCREF(__pyx_v_bonds);

  /* "/home/brandon/DANSE/cad/src/pyrex_test.pyx":23 */
  __pyx_v_tot = 0;

  /* "/home/brandon/DANSE/cad/src/pyrex_test.pyx":24 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  Py_INCREF(__pyx_v_mols);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_mols);
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_5 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  for (__pyx_1 = 0; __pyx_1 < __pyx_5; ++__pyx_1) {
    __pyx_2 = PyInt_FromLong(__pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_2;
    __pyx_2 = 0;

    /* "/home/brandon/DANSE/cad/src/pyrex_test.pyx":25 */
    __pyx_3 = PyObject_GetItem(__pyx_v_mols, __pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; goto __pyx_L1;}
    Py_DECREF(__pyx_v_mol);
    __pyx_v_mol = __pyx_3;
    __pyx_3 = 0;

    /* "/home/brandon/DANSE/cad/src/pyrex_test.pyx":26 */
    __pyx_4 = PyObject_GetAttr(__pyx_v_mol, __pyx_n_atoms); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
    __pyx_2 = PyObject_GetAttr(__pyx_4, __pyx_n_itervalues); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
    __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_2 = PyObject_GetIter(__pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    for (;;) {
      __pyx_L4:;
      __pyx_3 = PyIter_Next(__pyx_2);
      if (!__pyx_3) {
        if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
        break;
      }
      Py_DECREF(__pyx_v_atm);
      __pyx_v_atm = __pyx_3;
      __pyx_3 = 0;

      /* "/home/brandon/DANSE/cad/src/pyrex_test.pyx":27 */
      __pyx_4 = PyObject_GetAttr(__pyx_v_atm, __pyx_n_bonds); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; goto __pyx_L1;}
      Py_DECREF(__pyx_v_bonds);
      __pyx_v_bonds = __pyx_4;
      __pyx_4 = 0;

      /* "/home/brandon/DANSE/cad/src/pyrex_test.pyx":28 */
      __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
      __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
      Py_INCREF(__pyx_v_bonds);
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_bonds);
      __pyx_6 = PyObject_CallObject(__pyx_3, __pyx_4); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      __pyx_7 = PyInt_AsLong(__pyx_6); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      __pyx_v_nn = __pyx_7;

      /* "/home/brandon/DANSE/cad/src/pyrex_test.pyx":29 */
      __pyx_v_tot = (__pyx_v_tot + __pyx_v_nn);
    }
    __pyx_L5:;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/home/brandon/DANSE/cad/src/pyrex_test.pyx":30 */
  __pyx_3 = PyInt_FromLong(__pyx_v_tot); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("pyrex_test.nbonds");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_mol);
  Py_DECREF(__pyx_v_atm);
  Py_DECREF(__pyx_v_bonds);
  Py_DECREF(__pyx_v_mols);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n___author__, "__author__"},
  {&__pyx_n_atoms, "atoms"},
  {&__pyx_n_bonds, "bonds"},
  {&__pyx_n_bruce, "bruce"},
  {&__pyx_n_itervalues, "itervalues"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_nbonds, "nbonds"},
  {0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"nbonds", (PyCFunction)__pyx_f_10pyrex_test_nbonds, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10pyrex_test_nbonds},
  {0, 0, 0, 0}
};

DL_EXPORT(void) initpyrex_test(void); /*proto*/
DL_EXPORT(void) initpyrex_test(void) {
  __pyx_m = Py_InitModule4("pyrex_test", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};

  /* "/home/brandon/DANSE/cad/src/pyrex_test.pyx":16 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___author__, __pyx_n_bruce) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}

  /* "/home/brandon/DANSE/cad/src/pyrex_test.pyx":18 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("pyrex_test");
}

static char *__pyx_filenames[] = {
  "pyrex_test.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
