        file_menu = wx.Menu()
        file_menu.Append(ID_ColumnFile, "Load File: Column Data")
        file_menu.Append(ID_NetcdfFile, "Load Netcdf File")
        file_menu.Append(ID_SavePlot, "Save Plot")
        file_menu.Append(wx.ID_EXIT, "Exit")