# Install script for directory: /home/juju/VTK5.0/VTK/Wrapping/Tcl

MESSAGE(STATUS "Installing /home/juju/VTK5.0_Suse1032bits/lib/vtk-5.0/pkgIndex.tcl")
FILE(INSTALL DESTINATION "/home/juju/VTK5.0_Suse1032bits/lib/vtk-5.0" TYPE FILE FILES "/home/juju/VTK5.0/VTK/Wrapping/Tcl/Install/Hide/pkgIndex.tcl")
MESSAGE(STATUS "Installing /home/juju/VTK5.0_Suse1032bits/lib/vtk-5.0/tcl/README")
FILE(INSTALL DESTINATION "/home/juju/VTK5.0_Suse1032bits/lib/vtk-5.0/tcl" TYPE FILE FILES "/home/juju/VTK5.0/VTK/Wrapping/Tcl/README")
MESSAGE(STATUS "Installing /home/juju/VTK5.0_Suse1032bits/lib/vtk-5.0/tcl/vtktcl.c")
FILE(INSTALL DESTINATION "/home/juju/VTK5.0_Suse1032bits/lib/vtk-5.0/tcl" TYPE FILE FILES "/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtktcl.c")
MESSAGE(STATUS "Installing /home/juju/VTK5.0_Suse1032bits/bin/vtk")
FILE(INSTALL DESTINATION "/home/juju/VTK5.0_Suse1032bits/bin" TYPE EXECUTABLE FILES "/home/juju/VTK5.0/VTK/bin/vtk")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtk/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkbase/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkcommon/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkfiltering/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkgraphics/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkimaging/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkinteraction/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkio/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtktesting/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkparallel/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkwidgets/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkhybrid/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkvolumerendering/cmake_install.cmake")
INCLUDE("/home/juju/VTK5.0/VTK/Wrapping/Tcl/vtkrendering/cmake_install.cmake")

