@echo off
rem This file generated by Jython installer
rem Created on XXX by Sebastien
rem
rem set JAVA_HOME=C:\Program Files\Java\jre1.5.0_02

set ARGS=

:loop
if [%1] == [] goto end
        set ARGS=%ARGS% %1
        shift
        goto loop
:end



"C:\j2sdk1.4.2_06\bin\java.exe" "-Dpython.home=.\ThirdPart\jython-2.1" -classpath ".\ThirdPart\jython-2.1\jython.jar" org.python.util.jython %ARGS%

