# Vimm: Visual Interface to Materials Manipulation
#
# Copyright 2010 Caltech.  Copyright 2005 Sandia Corporation.  Under the terms of Contract
# DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government
# retains certain rights in this sofware.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  
# USA


import wx

class Sketcher(wx.Frame):
    def __init__(self, parent, id, **kwds):
        kwds['style'] = wx.MINIMIZE_BOX | wx.CAPTION
        kwds['title'] = "Sketching Options"
        wx.Frame.__init__(self, parent, id, **kwds)

#        self.SetBackgroundColour(wx.LIGHT_GREY)

        self.parent = parent
        self.atno = -1
        self.button_id = "Not yet"
        self.button_color = (0,0,0)

        self.create_widgets()
        self.set_background_color() # Have to do this because of Windows/Linux differences
        self.layout_page()
        return

    def create_widgets(self):
        #
        # Buttons for Periodic Table
        #
        self.blanks = []
        for i in range(40):
            self.blanks.append(wx.StaticText(self, -1, "", size=(45,45)))

        self.button_ids = []
        self.create_row_1()
        self.create_row_2()
        self.create_row_3()
        self.create_row_4()
        self.create_row_5()
        self.create_row_6()
        self.create_row_7()
        self.create_row_8()
        self.create_row_9()

        self.btnClear = wx.Button(self, -1, "Clear Screen")
        self.btnClose = wx.Button(self, -1, "Close")

        wx.EVT_BUTTON(self, self.btnClear.GetId(), self.clear)
        wx.EVT_BUTTON(self, self.btnClose.GetId(), self.close)

        return

    def set_background_color(self):
        color = self.btnClear.GetBackgroundColour()
        self.SetBackgroundColour(color)
        self.btnClear.SetBackgroundColour(color)
        self.btnClose.SetBackgroundColour(color)
        for blank in self.blanks:
            blank.SetBackgroundColour(color)
        return

    def create_row_1(self):
        self.btnH = wx.Button(self, -1, "1\nH", size=(45,45))
        self.btnHe = wx.Button(self, -1, "2\nHe", size=(45,45))

        self.btnH.SetBackgroundColour((0,0,255))
        self.btnHe.SetBackgroundColour((255,255,0))

        self.button_ids.append(self.btnH.GetId())
        self.button_ids.append(self.btnHe.GetId())

        wx.EVT_BUTTON(self, self.button_ids[0], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[1], self.set_atno)
        return

    def create_row_2(self):
        self.btnLi = wx.Button(self, -1, "3\nLi", size=(45,45))
        self.btnBe = wx.Button(self, -1, "4\nBe", size=(45,45))
        self.btnB = wx.Button(self, -1, "5\nB", size=(45,45))
        self.btnC = wx.Button(self, -1, "6\nC", size=(45,45))
        self.btnN = wx.Button(self, -1, "7\nN", size=(45,45))
        self.btnO = wx.Button(self, -1, "8\nO", size=(45,45))
        self.btnF = wx.Button(self, -1, "9\nF", size=(45,45))
        self.btnNe = wx.Button(self, -1, "10\nNe", size=(45,45))

        self.btnLi.SetBackgroundColour((0,0,255))
        self.btnBe.SetBackgroundColour((0,0,255))
        self.btnB.SetBackgroundColour((255,255,0))
        self.btnC.SetBackgroundColour((255,255,0))
        self.btnN.SetBackgroundColour((255,255,0))
        self.btnO.SetBackgroundColour((255,255,0))
        self.btnF.SetBackgroundColour((255,255,0))
        self.btnNe.SetBackgroundColour((255,255,0))

        self.button_ids.append(self.btnLi.GetId())
        self.button_ids.append(self.btnBe.GetId())
        self.button_ids.append(self.btnB.GetId())
        self.button_ids.append(self.btnC.GetId())
        self.button_ids.append(self.btnN.GetId())
        self.button_ids.append(self.btnO.GetId())
        self.button_ids.append(self.btnF.GetId())
        self.button_ids.append(self.btnNe.GetId())

        wx.EVT_BUTTON(self, self.button_ids[2], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[3], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[4], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[5], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[6], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[7], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[8], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[9], self.set_atno)
        return

    def create_row_3(self):
        self.btnNa = wx.Button(self, -1, "11\nNa", size=(45,45))
        self.btnMg = wx.Button(self, -1, "12\nMg", size=(45,45))
        self.btnAl = wx.Button(self, -1, "13\nAl", size=(45,45))
        self.btnSi = wx.Button(self, -1, "14\nSi", size=(45,45))
        self.btnP = wx.Button(self, -1, "15\nP", size=(45,45))
        self.btnS = wx.Button(self, -1, "16\nS", size=(45,45))
        self.btnCl = wx.Button(self, -1, "17\nCl", size=(45,45))
        self.btnAr = wx.Button(self, -1, "18\nAr", size=(45,45))

        self.btnNa.SetBackgroundColour((0,0,255))
        self.btnMg.SetBackgroundColour((0,0,255))
        self.btnAl.SetBackgroundColour((255,255,0))
        self.btnSi.SetBackgroundColour((255,255,0))
        self.btnP.SetBackgroundColour((255,255,0))
        self.btnS.SetBackgroundColour((255,255,0))
        self.btnCl.SetBackgroundColour((255,255,0))
        self.btnAr.SetBackgroundColour((255,255,0))

        self.button_ids.append(self.btnNa.GetId())
        self.button_ids.append(self.btnMg.GetId())
        self.button_ids.append(self.btnAl.GetId())
        self.button_ids.append(self.btnSi.GetId())
        self.button_ids.append(self.btnP.GetId())
        self.button_ids.append(self.btnS.GetId())
        self.button_ids.append(self.btnCl.GetId())
        self.button_ids.append(self.btnAr.GetId())

        wx.EVT_BUTTON(self, self.button_ids[10], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[11], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[12], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[12], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[14], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[15], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[16], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[17], self.set_atno)
        return

    def create_row_4(self):
        self.btnK = wx.Button(self, -1, "19\nK", size=(45,45))
        self.btnCa = wx.Button(self, -1, "20\nCa", size=(45,45))
        self.btnSc = wx.Button(self, -1, "21\nSc", size=(45,45))
        self.btnTi = wx.Button(self, -1, "22\nTi", size=(45,45))
        self.btnV = wx.Button(self, -1, "23\nV", size=(45,45))
        self.btnCr = wx.Button(self, -1, "24\nCr", size=(45,45))
        self.btnMn = wx.Button(self, -1, "25\nMn", size=(45,45))
        self.btnFe = wx.Button(self, -1, "26\nFe", size=(45,45))
        self.btnCo = wx.Button(self, -1, "27\nCo", size=(45,45))
        self.btnNi = wx.Button(self, -1, "28\nNi", size=(45,45))
        self.btnCu = wx.Button(self, -1, "29\nCu", size=(45,45))
        self.btnZn = wx.Button(self, -1, "30\nZn", size=(45,45))
        self.btnGa = wx.Button(self, -1, "31\nGa", size=(45,45))
        self.btnGe = wx.Button(self, -1, "32\nGe", size=(45,45))
        self.btnAs = wx.Button(self, -1, "33\nAs", size=(45,45))
        self.btnSe = wx.Button(self, -1, "34\nSe", size=(45,45))
        self.btnBr = wx.Button(self, -1, "35\nBr", size=(45,45))
        self.btnKr = wx.Button(self, -1, "36\nKr", size=(45,45))

        self.btnK.SetBackgroundColour((0,0,255))
        self.btnCa.SetBackgroundColour((0,0,255))
        self.btnSc.SetBackgroundColour((255,0,0))
        self.btnTi.SetBackgroundColour((255,0,0))
        self.btnV.SetBackgroundColour((255,0,0))
        self.btnCr.SetBackgroundColour((255,0,0))
        self.btnMn.SetBackgroundColour((255,0,0))
        self.btnFe.SetBackgroundColour((255,0,0))
        self.btnCo.SetBackgroundColour((255,0,0))
        self.btnNi.SetBackgroundColour((255,0,0))
        self.btnCu.SetBackgroundColour((255,0,0))
        self.btnZn.SetBackgroundColour((255,0,0))
        self.btnGa.SetBackgroundColour((255,255,0))
        self.btnGe.SetBackgroundColour((255,255,0))
        self.btnAs.SetBackgroundColour((255,255,0))
        self.btnSe.SetBackgroundColour((255,255,0))
        self.btnBr.SetBackgroundColour((255,255,0))
        self.btnKr.SetBackgroundColour((255,255,0))

        self.button_ids.append(self.btnK.GetId())
        self.button_ids.append(self.btnCa.GetId())
        self.button_ids.append(self.btnSc.GetId())
        self.button_ids.append(self.btnTi.GetId())
        self.button_ids.append(self.btnV.GetId())
        self.button_ids.append(self.btnCr.GetId())
        self.button_ids.append(self.btnMn.GetId())
        self.button_ids.append(self.btnFe.GetId())
        self.button_ids.append(self.btnCo.GetId())
        self.button_ids.append(self.btnNi.GetId())
        self.button_ids.append(self.btnCu.GetId())
        self.button_ids.append(self.btnZn.GetId())
        self.button_ids.append(self.btnGa.GetId())
        self.button_ids.append(self.btnGe.GetId())
        self.button_ids.append(self.btnAs.GetId())
        self.button_ids.append(self.btnSe.GetId())
        self.button_ids.append(self.btnBr.GetId())
        self.button_ids.append(self.btnKr.GetId())

        wx.EVT_BUTTON(self, self.button_ids[18], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[19], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[20], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[21], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[22], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[23], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[24], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[25], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[26], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[27], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[28], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[29], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[30], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[31], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[32], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[33], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[34], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[35], self.set_atno)
        return

    def create_row_5(self):
        self.btnRb = wx.Button(self, -1, "37\nRb", size=(45,45))
        self.btnSr = wx.Button(self, -1, "38\nSr", size=(45,45))
        self.btnY = wx.Button(self, -1, "39\nY", size=(45,45))
        self.btnZr = wx.Button(self, -1, "40\nZr", size=(45,45))
        self.btnNb = wx.Button(self, -1, "41\nNb", size=(45,45))
        self.btnMo = wx.Button(self, -1, "42\nMo", size=(45,45))
        self.btnTc = wx.Button(self, -1, "43\nTc", size=(45,45))
        self.btnRu = wx.Button(self, -1, "44\nRu", size=(45,45))
        self.btnRh = wx.Button(self, -1, "45\nRh", size=(45,45))
        self.btnPd = wx.Button(self, -1, "46\nPd", size=(45,45))
        self.btnAg = wx.Button(self, -1, "47\nAg", size=(45,45))
        self.btnCd = wx.Button(self, -1, "48\nCd", size=(45,45))
        self.btnIn = wx.Button(self, -1, "49\nIn", size=(45,45))
        self.btnSn = wx.Button(self, -1, "50\nSn", size=(45,45))
        self.btnSb = wx.Button(self, -1, "51\nSb", size=(45,45))
        self.btnTe = wx.Button(self, -1, "52\nTe", size=(45,45))
        self.btnI = wx.Button(self, -1, "53\nI", size=(45,45))
        self.btnXe = wx.Button(self, -1, "54\nXe", size=(45,45))

        self.btnRb.SetBackgroundColour((0,0,255))
        self.btnSr.SetBackgroundColour((0,0,255))
        self.btnY.SetBackgroundColour((255,0,0))
        self.btnZr.SetBackgroundColour((255,0,0))
        self.btnNb.SetBackgroundColour((255,0,0))
        self.btnMo.SetBackgroundColour((255,0,0))
        self.btnTc.SetBackgroundColour((255,0,0))
        self.btnRu.SetBackgroundColour((255,0,0))
        self.btnRh.SetBackgroundColour((255,0,0))
        self.btnPd.SetBackgroundColour((255,0,0))
        self.btnAg.SetBackgroundColour((255,0,0))
        self.btnCd.SetBackgroundColour((255,0,0))
        self.btnIn.SetBackgroundColour((255,255,0))
        self.btnSn.SetBackgroundColour((255,255,0))
        self.btnSb.SetBackgroundColour((255,255,0))
        self.btnTe.SetBackgroundColour((255,255,0))
        self.btnI.SetBackgroundColour((255,255,0))
        self.btnXe.SetBackgroundColour((255,255,0))

        self.button_ids.append(self.btnRb.GetId())
        self.button_ids.append(self.btnSr.GetId())
        self.button_ids.append(self.btnY.GetId())
        self.button_ids.append(self.btnZr.GetId())
        self.button_ids.append(self.btnNb.GetId())
        self.button_ids.append(self.btnMo.GetId())
        self.button_ids.append(self.btnTc.GetId())
        self.button_ids.append(self.btnRu.GetId())
        self.button_ids.append(self.btnRh.GetId())
        self.button_ids.append(self.btnPd.GetId())
        self.button_ids.append(self.btnAg.GetId())
        self.button_ids.append(self.btnCd.GetId())
        self.button_ids.append(self.btnIn.GetId())
        self.button_ids.append(self.btnSn.GetId())
        self.button_ids.append(self.btnSb.GetId())
        self.button_ids.append(self.btnTe.GetId())
        self.button_ids.append(self.btnI.GetId())
        self.button_ids.append(self.btnXe.GetId())

        wx.EVT_BUTTON(self, self.button_ids[36], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[37], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[38], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[39], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[40], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[41], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[42], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[43], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[44], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[45], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[46], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[47], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[48], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[49], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[50], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[51], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[52], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[53], self.set_atno)
        return

    def create_row_6(self):
        self.btnCs = wx.Button(self, -1, "55\nCs", size=(45,45))
        self.btnBa = wx.Button(self, -1, "56\nBa", size=(45,45))
        self.btnLu = wx.Button(self, -1, "71\nLu", size=(45,45))
        self.btnHf = wx.Button(self, -1, "72\nHf", size=(45,45))
        self.btnTa = wx.Button(self, -1, "73\nTa", size=(45,45))
        self.btnW = wx.Button(self, -1, "74\nW", size=(45,45))
        self.btnRe = wx.Button(self, -1, "75\nRe", size=(45,45))
        self.btnOs = wx.Button(self, -1, "76\nOs", size=(45,45))
        self.btnIr = wx.Button(self, -1, "77\nIr", size=(45,45))
        self.btnPt = wx.Button(self, -1, "78\nPt", size=(45,45))
        self.btnAu = wx.Button(self, -1, "79\nAu", size=(45,45))
        self.btnHg = wx.Button(self, -1, "80\nHg", size=(45,45))
        self.btnTl = wx.Button(self, -1, "81\nTl", size=(45,45))
        self.btnPb = wx.Button(self, -1, "82\nPb", size=(45,45))
        self.btnBi = wx.Button(self, -1, "83\nBi", size=(45,45))
        self.btnPo = wx.Button(self, -1, "84\nPo", size=(45,45))
        self.btnAt = wx.Button(self, -1, "85\nAt", size=(45,45))
        self.btnRn = wx.Button(self, -1, "86\nRn", size=(45,45))

        self.btnCs.SetBackgroundColour((0,0,255))
        self.btnBa.SetBackgroundColour((0,0,255))
        self.btnLu.SetBackgroundColour((255,0,0))
        self.btnHf.SetBackgroundColour((255,0,0))
        self.btnTa.SetBackgroundColour((255,0,0))
        self.btnW.SetBackgroundColour((255,0,0))
        self.btnRe.SetBackgroundColour((255,0,0))
        self.btnOs.SetBackgroundColour((255,0,0))
        self.btnIr.SetBackgroundColour((255,0,0))
        self.btnPt.SetBackgroundColour((255,0,0))
        self.btnAu.SetBackgroundColour((255,0,0))
        self.btnHg.SetBackgroundColour((255,0,0))
        self.btnTl.SetBackgroundColour((255,255,0))
        self.btnPb.SetBackgroundColour((255,255,0))
        self.btnBi.SetBackgroundColour((255,255,0))
        self.btnPo.SetBackgroundColour((255,255,0))
        self.btnAt.SetBackgroundColour((255,255,0))
        self.btnRn.SetBackgroundColour((255,255,0))

        self.button_ids.append(self.btnCs.GetId())
        self.button_ids.append(self.btnBa.GetId())
        self.button_ids.append(self.btnLu.GetId())
        self.button_ids.append(self.btnHf.GetId())
        self.button_ids.append(self.btnTa.GetId())
        self.button_ids.append(self.btnW.GetId())
        self.button_ids.append(self.btnRe.GetId())
        self.button_ids.append(self.btnOs.GetId())
        self.button_ids.append(self.btnIr.GetId())
        self.button_ids.append(self.btnPt.GetId())
        self.button_ids.append(self.btnAu.GetId())
        self.button_ids.append(self.btnHg.GetId())
        self.button_ids.append(self.btnTl.GetId())
        self.button_ids.append(self.btnPb.GetId())
        self.button_ids.append(self.btnBi.GetId())
        self.button_ids.append(self.btnPo.GetId())
        self.button_ids.append(self.btnAt.GetId())
        self.button_ids.append(self.btnRn.GetId())

        wx.EVT_BUTTON(self, self.button_ids[54], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[55], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[56], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[57], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[58], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[59], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[60], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[61], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[62], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[63], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[64], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[65], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[66], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[67], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[68], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[69], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[70], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[71], self.set_atno)
        return

    def create_row_7(self):
        self.btnFr = wx.Button(self, -1, "87\nFr", size=(45,45))
        self.btnRa = wx.Button(self, -1, "88\nRa", size=(45,45))
        self.btnLr = wx.Button(self, -1, "103\nLr", size=(45,45))
        self.btnRf = wx.Button(self, -1, "104\nRf", size=(45,45))
        self.btnDb = wx.Button(self, -1, "105\nDb", size=(45,45))
        self.btnSg = wx.Button(self, -1, "106\nSg", size=(45,45))
        self.btnBh = wx.Button(self, -1, "107\nBh", size=(45,45))
        self.btnHs = wx.Button(self, -1, "108\nHs", size=(45,45))
        self.btnMt = wx.Button(self, -1, "109\nMt", size=(45,45))
        self.btnDs = wx.Button(self, -1, "110\nDs", size=(45,45))
        self.btnRg = wx.Button(self, -1, "111\nRg", size=(45,45))
        self.btnUub = wx.Button(self, -1, "112\nUub", size=(45,45))
        self.btnUut = wx.Button(self, -1, "113\nUut", size=(45,45))
        self.btnUuq = wx.Button(self, -1, "114\nUuq", size=(45,45))
        self.btnUup = wx.Button(self, -1, "115\nUup", size=(45,45))
        self.btnUuh = wx.Button(self, -1, "116\nUuh", size=(45,45))
        self.btnUus = wx.Button(self, -1, "117\nUus", size=(45,45))
        self.btnUuo = wx.Button(self, -1, "118\nUuo", size=(45,45))

        self.btnFr.SetBackgroundColour((0,0,255))
        self.btnRa.SetBackgroundColour((0,0,255))
        self.btnLr.SetBackgroundColour((255,0,0))
        self.btnRf.SetBackgroundColour((255,0,0))
        self.btnDb.SetBackgroundColour((255,0,0))
        self.btnSg.SetBackgroundColour((255,0,0))
        self.btnBh.SetBackgroundColour((255,0,0))
        self.btnHs.SetBackgroundColour((255,0,0))
        self.btnMt.SetBackgroundColour((255,0,0))
        self.btnDs.SetBackgroundColour((255,0,0))
        self.btnRg.SetBackgroundColour((255,0,0))
        self.btnUub.SetBackgroundColour((255,0,0))
        self.btnUut.SetBackgroundColour((255,255,0))
        self.btnUuq.SetBackgroundColour((255,255,0))
        self.btnUup.SetBackgroundColour((255,255,0))
        self.btnUuh.SetBackgroundColour((255,255,0))
        self.btnUus.SetBackgroundColour((255,255,0))
        self.btnUuo.SetBackgroundColour((255,255,0))

        self.button_ids.append(self.btnFr.GetId())
        self.button_ids.append(self.btnRa.GetId())
        self.button_ids.append(self.btnLr.GetId())
        self.button_ids.append(self.btnRf.GetId())
        self.button_ids.append(self.btnDb.GetId())
        self.button_ids.append(self.btnSg.GetId())
        self.button_ids.append(self.btnBh.GetId())
        self.button_ids.append(self.btnHs.GetId())
        self.button_ids.append(self.btnMt.GetId())
        self.button_ids.append(self.btnDs.GetId())
        self.button_ids.append(self.btnRg.GetId())
        self.button_ids.append(self.btnUub.GetId())
        self.button_ids.append(self.btnUut.GetId())
        self.button_ids.append(self.btnUuq.GetId())
        self.button_ids.append(self.btnUup.GetId())
        self.button_ids.append(self.btnUuh.GetId())
        self.button_ids.append(self.btnUus.GetId())
        self.button_ids.append(self.btnUuo.GetId())

        wx.EVT_BUTTON(self, self.button_ids[72], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[73], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[74], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[75], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[76], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[77], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[78], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[79], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[80], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[81], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[82], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[83], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[84], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[85], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[86], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[87], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[88], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[89], self.set_atno)
        return

    def create_row_8(self):
        self.lblLanthanoids = wx.StaticText(self, -1, "Lanthanoids", size=(94,-1), style=wx.ALIGN_CENTRE)
        self.btnLa = wx.Button(self, -1, "57\nLa", size=(45,45))
        self.btnCe = wx.Button(self, -1, "58\nCe", size=(45,45))
        self.btnPr = wx.Button(self, -1, "59\nPr", size=(45,45))
        self.btnNd = wx.Button(self, -1, "60\nNd", size=(45,45))
        self.btnPm = wx.Button(self, -1, "61\nPm", size=(45,45))
        self.btnSm = wx.Button(self, -1, "62\nSm", size=(45,45))
        self.btnEu = wx.Button(self, -1, "63\nEu", size=(45,45))
        self.btnGd = wx.Button(self, -1, "64\nGd", size=(45,45))
        self.btnTb = wx.Button(self, -1, "65\nTb", size=(45,45))
        self.btnDy = wx.Button(self, -1, "66\nDy", size=(45,45))
        self.btnHo = wx.Button(self, -1, "67\nHo", size=(45,45))
        self.btnEr = wx.Button(self, -1, "68\nEr", size=(45,45))
        self.btnTm = wx.Button(self, -1, "69\nTm", size=(45,45))
        self.btnYb = wx.Button(self, -1, "70\nYb", size=(45,45))

        self.btnLa.SetBackgroundColour((0,255,0))
        self.btnCe.SetBackgroundColour((0,255,0))
        self.btnPr.SetBackgroundColour((0,255,0))
        self.btnNd.SetBackgroundColour((0,255,0))
        self.btnPm.SetBackgroundColour((0,255,0))
        self.btnSm.SetBackgroundColour((0,255,0))
        self.btnEu.SetBackgroundColour((0,255,0))
        self.btnGd.SetBackgroundColour((0,255,0))
        self.btnTb.SetBackgroundColour((0,255,0))
        self.btnDy.SetBackgroundColour((0,255,0))
        self.btnHo.SetBackgroundColour((0,255,0))
        self.btnEr.SetBackgroundColour((0,255,0))
        self.btnTm.SetBackgroundColour((0,255,0))
        self.btnYb.SetBackgroundColour((0,255,0))

        self.button_ids.insert(56, self.btnLa.GetId())
        self.button_ids.insert(57, self.btnCe.GetId())
        self.button_ids.insert(58, self.btnPr.GetId())
        self.button_ids.insert(59, self.btnNd.GetId())
        self.button_ids.insert(60, self.btnPm.GetId())
        self.button_ids.insert(61, self.btnSm.GetId())
        self.button_ids.insert(62, self.btnEu.GetId())
        self.button_ids.insert(63, self.btnGd.GetId())
        self.button_ids.insert(64, self.btnTb.GetId())
        self.button_ids.insert(65, self.btnDy.GetId())
        self.button_ids.insert(66, self.btnHo.GetId())
        self.button_ids.insert(67, self.btnEr.GetId())
        self.button_ids.insert(68, self.btnTm.GetId())
        self.button_ids.insert(69, self.btnYb.GetId())

        wx.EVT_BUTTON(self, self.button_ids[56], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[57], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[58], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[59], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[60], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[61], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[62], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[63], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[64], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[65], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[66], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[67], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[68], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[69], self.set_atno)
        return

    def create_row_9(self):
        self.lblActinoids = wx.StaticText(self, -1, "Actinoids", size=(94,-1), style=wx.ALIGN_CENTRE)
        self.btnAc = wx.Button(self, -1, "89\nAc", size=(45,45))
        self.btnTh = wx.Button(self, -1, "90\nTh", size=(45,45))
        self.btnPa = wx.Button(self, -1, "91\nPa", size=(45,45))
        self.btnU = wx.Button(self, -1, "92\nU", size=(45,45))
        self.btnNp = wx.Button(self, -1, "93\nNp", size=(45,45))
        self.btnPu = wx.Button(self, -1, "94\nPu", size=(45,45))
        self.btnAm = wx.Button(self, -1, "95\nAm", size=(45,45))
        self.btnCm = wx.Button(self, -1, "98\nCm", size=(45,45))
        self.btnBk = wx.Button(self, -1, "97\nBk", size=(45,45))
        self.btnCf = wx.Button(self, -1, "98\nCf", size=(45,45))
        self.btnEs = wx.Button(self, -1, "99\nEs", size=(45,45))
        self.btnFm = wx.Button(self, -1, "100\nFm", size=(45,45))
        self.btnMd = wx.Button(self, -1, "101\nMd", size=(45,45))
        self.btnNo = wx.Button(self, -1, "102\nNo", size=(45,45))

        self.btnAc.SetBackgroundColour((0,255,0))
        self.btnTh.SetBackgroundColour((0,255,0))
        self.btnPa.SetBackgroundColour((0,255,0))
        self.btnU.SetBackgroundColour((0,255,0))
        self.btnNp.SetBackgroundColour((0,255,0))
        self.btnPu.SetBackgroundColour((0,255,0))
        self.btnAm.SetBackgroundColour((0,255,0))
        self.btnCm.SetBackgroundColour((0,255,0))
        self.btnBk.SetBackgroundColour((0,255,0))
        self.btnCf.SetBackgroundColour((0,255,0))
        self.btnEs.SetBackgroundColour((0,255,0))
        self.btnFm.SetBackgroundColour((0,255,0))
        self.btnMd.SetBackgroundColour((0,255,0))
        self.btnNo.SetBackgroundColour((0,255,0))

        self.button_ids.insert(88, self.btnAc.GetId())
        self.button_ids.insert(89, self.btnTh.GetId())
        self.button_ids.insert(90, self.btnPa.GetId())
        self.button_ids.insert(91, self.btnU.GetId())
        self.button_ids.insert(92, self.btnNp.GetId())
        self.button_ids.insert(93, self.btnPu.GetId())
        self.button_ids.insert(94, self.btnAm.GetId())
        self.button_ids.insert(95, self.btnCm.GetId())
        self.button_ids.insert(96, self.btnBk.GetId())
        self.button_ids.insert(97, self.btnCf.GetId())
        self.button_ids.insert(98, self.btnEs.GetId())
        self.button_ids.insert(99, self.btnFm.GetId())
        self.button_ids.insert(100, self.btnMd.GetId())
        self.button_ids.insert(101, self.btnNo.GetId())

        wx.EVT_BUTTON(self, self.button_ids[88], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[89], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[90], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[91], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[92], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[93], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[94], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[95], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[96], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[97], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[98], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[99], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[100], self.set_atno)
        wx.EVT_BUTTON(self, self.button_ids[101], self.set_atno)
        return

    def layout_page(self):
        szrMain = wx.BoxSizer(wx.VERTICAL)
        szrPeriodicTable = wx.BoxSizer(wx.VERTICAL)
        szrPTRow1 = wx.BoxSizer(wx.HORIZONTAL)
        szrPTRow2 = wx.BoxSizer(wx.HORIZONTAL)
        szrPTRow3 = wx.BoxSizer(wx.HORIZONTAL)
        szrPTRow4 = wx.BoxSizer(wx.HORIZONTAL)
        szrPTRow5 = wx.BoxSizer(wx.HORIZONTAL)
        szrPTRow6 = wx.BoxSizer(wx.HORIZONTAL)
        szrPTRow7 = wx.BoxSizer(wx.HORIZONTAL)
        szrPTRow8 = wx.BoxSizer(wx.HORIZONTAL)
        szrPTRow9 = wx.BoxSizer(wx.HORIZONTAL)
        szrButtons = wx.BoxSizer(wx.HORIZONTAL)

        szrPTRow1.Add(self.btnH, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        for i in range(16):
            szrPTRow1.Add(self.blanks[i], 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow1.Add(self.btnHe, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)

        szrPTRow2.Add(self.btnLi, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow2.Add(self.btnBe, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        for i in range(16, 26):
            szrPTRow2.Add(self.blanks[i], 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow2.Add(self.btnB, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow2.Add(self.btnC, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow2.Add(self.btnN, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow2.Add(self.btnO, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow2.Add(self.btnF, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow2.Add(self.btnNe, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)

        szrPTRow3.Add(self.btnNa, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow3.Add(self.btnMg, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        for i in range(26, 36):
            szrPTRow3.Add(self.blanks[i], 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow3.Add(self.btnAl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow3.Add(self.btnSi, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow3.Add(self.btnP, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow3.Add(self.btnS, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow3.Add(self.btnCl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow3.Add(self.btnAr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)

        szrPTRow4.Add(self.btnK, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnCa, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnSc, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnTi, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnV, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnCr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnMn, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnFe, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnCo, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnNi, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnCu, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnZn, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnGa, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnGe, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnAs, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnSe, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnBr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow4.Add(self.btnKr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)

        szrPTRow5.Add(self.btnRb, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnSr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnY, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnZr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnNb, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnMo, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnTc, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnRu, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnRh, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnPd, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnAg, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnCd, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnIn, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnSn, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnSb, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnTe, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnI, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow5.Add(self.btnXe, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)

        szrPTRow6.Add(self.btnCs, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnBa, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnLu, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnHf, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnTa, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnW, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnRe, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnOs, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnIr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnPt, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnAu, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnHg, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnTl, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnPb, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnBi, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnPo, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnAt, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow6.Add(self.btnRn, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)

        szrPTRow7.Add(self.btnFr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnRa, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnLr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnRf, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnDb, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnSg, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnBh, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnHs, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnMt, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnDs, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnRg, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnUub, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnUut, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnUuq, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnUup, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnUuh, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnUus, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow7.Add(self.btnUuo, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)

        szrPTRow8.Add(self.lblLanthanoids, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnLa, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnCe, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnPr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnNd, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnPm, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnSm, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnEu, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnGd, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnTb, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnDy, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnHo, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnEr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnTm, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow8.Add(self.btnYb, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        for i in range(36, 38):
            szrPTRow8.Add(self.blanks[i], 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)

        szrPTRow9.Add(self.lblActinoids, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnAc, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnTh, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnPa, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnU, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnNp, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnPu, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnAm, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnCm, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnBk, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnCf, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnEs, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnFm, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnMd, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        szrPTRow9.Add(self.btnNo, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)
        for i in range(38, 40):
            szrPTRow9.Add(self.blanks[i], 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 2)

        szrPeriodicTable.Add(szrPTRow1, 0,wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL, 0) 
        szrPeriodicTable.Add(szrPTRow2, 0,wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL, 0) 
        szrPeriodicTable.Add(szrPTRow3, 0,wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL, 0) 
        szrPeriodicTable.Add(szrPTRow4, 0,wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL, 0) 
        szrPeriodicTable.Add(szrPTRow5, 0,wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL, 0) 
        szrPeriodicTable.Add(szrPTRow6, 0,wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL, 0) 
        szrPeriodicTable.Add(szrPTRow7, 0,wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL, 0) 
        szrPeriodicTable.Add(szrPTRow8, 0,wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL, 0) 
        szrPeriodicTable.Add(szrPTRow9, 0,wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL, 0) 

        szrButtons.Add(self.btnClear, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5)
        szrButtons.Add(self.btnClose, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5)

        szrMain.Add(szrPeriodicTable, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 15)
        szrMain.Add(szrButtons, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5)
        
        self.SetAutoLayout(1)
        self.SetSizer(szrMain)
        szrMain.Fit(self)
        szrMain.SetSizeHints(self)
        self.Layout()
        self.Centre()
        return

    def set_atno(self, evt):
        if self.button_id != "Not yet":
            old_button = self.FindWindowById(self.button_id)
            old_button.SetBackgroundColour(self.button_color)

        self.button_id = evt.GetId()
        self.atno = int(self.button_ids.index(self.button_id)) + 1

        selected_button = self.FindWindowById(self.button_id)
        self.button_color = selected_button.GetBackgroundColour()
        selected_button.SetBackgroundColour((255,255,255))
        return

    def clear(self, *args):
        if self.parent.canvas.shapes:
            self.parent.canvas.shapes.clear()
            self.parent.material.geo.clear()
            self.parent.canvas.InitGL()
            self.parent.canvas.Refresh()
        return

    def close(self, *args):
        self.parent.canvas.set_sketching(False)
        self.Close(True)
        return
